import Banner from "@/components/Banner";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import { Data } from "./api/productdata";
import Products from "@/components/Products";

export interface Props {
  productData: Data
}

export default function Home({productData}: Props) {
  
  return (
    <>
      <Head>
        <title>KaypaStore | Save Money. Live Better</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/tabLogo.ico" />
      </Head>
      <main className="bg-lightBlue">
        <Navbar />
        <div className="max-w-contentContainer mx-auto">
          <Banner />
          <Products productData={productData} />
        </div>
      </main>
    </>
  );
}


export const getServerSideProps = async () => {
  const productData = await (await fetch('http://localhost:3000/api/productdata'))
  .json()

  return {
    props: {productData}
  }
}